
server:
  port: 8080

spring:
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5432/product
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        formatSql: true
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true


