#postgresql-database
#server:
#  port: 8080
#
#spring:
#  datasource:
#    password: postgres
#    url: jdbc:postgresql://localhost:5432/product
#    username: postgres
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate:
#        formatSql: true
#        dialect: org.hibernate.dialect.PostgreSQL9Dialect
#    show-sql: true

##h2-database
#server:
#  port: 8080
#
#spring:
#  datasource:
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password: password
#    driver-class-name: org.h2.Driver
#  jpa:
#
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
#
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#  h2:
#    console:
#      enabled: true

#MySql-Database
spring:
  datasource:
    url: jdbc:mysql://mysqldb:3306/products_db?useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect










